name: 'Auto label PRs and issues'

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Auto label using file patterns
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
