name: 'Mark stale issues'

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  issues:
    types: [opened, labeled]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v6
        with:
          repo-token: 
            ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because there has been no activity for a while.
            If you think this is still relevant, please leave a comment or re-open it.
          days-before-stale: 30
          days-before-close: 7
          only-labels: 'needs-triage'
          exempt-labels: 'good first issue,help wanted'
